//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPack
    {
        public int ActionId { get; set; }
        public int PackId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Actions Actions { get; set; }
        public virtual Pack Pack { get; set; }
    }
}
