//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public Actions()
        {
            this.ActionDirection = new HashSet<ActionDirection>();
            this.ActionPack = new HashSet<ActionPack>();
            this.ActionPartner = new HashSet<ActionPartner>();
            this.ActionPlace = new HashSet<ActionPlace>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime DateTo { get; set; }
        public System.DateTime DateFrom { get; set; }
        public string Description { get; set; }
        public int ActionTypeId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Gift { get; set; }
        public bool IsVisible { get; set; }
        public System.DateTime ActionDateTo { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> Rate { get; set; }
        public string TrName { get; set; }
        public string Tag { get; set; }
    
        public virtual ICollection<ActionDirection> ActionDirection { get; set; }
        public virtual ICollection<ActionPack> ActionPack { get; set; }
        public virtual ICollection<ActionPartner> ActionPartner { get; set; }
        public virtual ICollection<ActionPlace> ActionPlace { get; set; }
        public virtual ActionType ActionType { get; set; }
        public virtual Image Image { get; set; }
    }
}
