//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cookie
    {
        public Cookie()
        {
            this.CookieLog = new HashSet<CookieLog>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string StartPointUrl { get; set; }
        public string StartPointController { get; set; }
        public string StartPointAction { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<CookieLog> CookieLog { get; set; }
    }
}
