//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction
    {
        public Direction()
        {
            this.ActionDirection = new HashSet<ActionDirection>();
            this.Gallery = new HashSet<Gallery>();
            this.Places = new HashSet<Places>();
            this.Portfolio = new HashSet<Portfolio>();
            this.Slider = new HashSet<Slider>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public string TrName { get; set; }
        public string UrlImg { get; set; }
        public string Description { get; set; }
        public string UrlVideo { get; set; }
        public bool IsVisible { get; set; }
        public string Сurrency { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string KeyWords { get; set; }
        public int Rate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> SeasonDateStart { get; set; }
        public Nullable<System.DateTime> SeasonDateEnd { get; set; }
    
        public virtual ICollection<ActionDirection> ActionDirection { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Gallery> Gallery { get; set; }
        public virtual ICollection<Places> Places { get; set; }
        public virtual ICollection<Portfolio> Portfolio { get; set; }
        public virtual ICollection<Slider> Slider { get; set; }
    }
}
