//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Client { get; set; }
        public int AvaId { get; set; }
        public string VK { get; set; }
        public string FB { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Portfolio { get; set; }
        public bool IsVisibled { get; set; }
    }
}
