//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Actions = new HashSet<Actions>();
            this.Blog = new HashSet<Blog>();
            this.Blog1 = new HashSet<Blog>();
            this.Blog2 = new HashSet<Blog>();
            this.Blog3 = new HashSet<Blog>();
            this.Blog4 = new HashSet<Blog>();
            this.Blog5 = new HashSet<Blog>();
            this.Blog6 = new HashSet<Blog>();
            this.Blog7 = new HashSet<Blog>();
            this.Blog8 = new HashSet<Blog>();
            this.Blog9 = new HashSet<Blog>();
            this.Blog10 = new HashSet<Blog>();
            this.Partners = new HashSet<Partners>();
            this.Partners1 = new HashSet<Partners>();
            this.Partners2 = new HashSet<Partners>();
            this.Places = new HashSet<Places>();
            this.Places1 = new HashSet<Places>();
            this.Portfolio = new HashSet<Portfolio>();
            this.Portfolio1 = new HashSet<Portfolio>();
            this.Portfolio2 = new HashSet<Portfolio>();
            this.Portfolio3 = new HashSet<Portfolio>();
            this.Portfolio4 = new HashSet<Portfolio>();
            this.Portfolio5 = new HashSet<Portfolio>();
            this.Portfolio6 = new HashSet<Portfolio>();
            this.Portfolio7 = new HashSet<Portfolio>();
            this.Portfolio8 = new HashSet<Portfolio>();
            this.Portfolio9 = new HashSet<Portfolio>();
            this.Portfolio10 = new HashSet<Portfolio>();
        }
    
        public int Id { get; set; }
        public byte[] Data { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OtKuda { get; set; }
    
        public virtual ICollection<Actions> Actions { get; set; }
        public virtual ICollection<Blog> Blog { get; set; }
        public virtual ICollection<Blog> Blog1 { get; set; }
        public virtual ICollection<Blog> Blog2 { get; set; }
        public virtual ICollection<Blog> Blog3 { get; set; }
        public virtual ICollection<Blog> Blog4 { get; set; }
        public virtual ICollection<Blog> Blog5 { get; set; }
        public virtual ICollection<Blog> Blog6 { get; set; }
        public virtual ICollection<Blog> Blog7 { get; set; }
        public virtual ICollection<Blog> Blog8 { get; set; }
        public virtual ICollection<Blog> Blog9 { get; set; }
        public virtual ICollection<Blog> Blog10 { get; set; }
        public virtual ICollection<Partners> Partners { get; set; }
        public virtual ICollection<Partners> Partners1 { get; set; }
        public virtual ICollection<Partners> Partners2 { get; set; }
        public virtual ICollection<Places> Places { get; set; }
        public virtual ICollection<Places> Places1 { get; set; }
        public virtual ICollection<Portfolio> Portfolio { get; set; }
        public virtual ICollection<Portfolio> Portfolio1 { get; set; }
        public virtual ICollection<Portfolio> Portfolio2 { get; set; }
        public virtual ICollection<Portfolio> Portfolio3 { get; set; }
        public virtual ICollection<Portfolio> Portfolio4 { get; set; }
        public virtual ICollection<Portfolio> Portfolio5 { get; set; }
        public virtual ICollection<Portfolio> Portfolio6 { get; set; }
        public virtual ICollection<Portfolio> Portfolio7 { get; set; }
        public virtual ICollection<Portfolio> Portfolio8 { get; set; }
        public virtual ICollection<Portfolio> Portfolio9 { get; set; }
        public virtual ICollection<Portfolio> Portfolio10 { get; set; }
    }
}
