//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainImages
    {
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string WhiteText { get; set; }
        public string RedText { get; set; }
    }
}
