//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacketService
    {
        public int PacketId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Packet Packet { get; set; }
        public virtual Service Service { get; set; }
    }
}
