//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_old
    {
        public Partner_old()
        {
            this.Portfolio = new HashSet<Portfolio>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CategoryId { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string TrName { get; set; }
        public byte[] Image { get; set; }
        public byte[] Avatar { get; set; }
        public string City { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Profession { get; set; }
        public string Viezd { get; set; }
        public string Phone { get; set; }
        public string Site { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public string Facebook { get; set; }
        public string Vk { get; set; }
        public bool IsEnabled { get; set; }
        public byte[] ImageProfile { get; set; }
        public int Rate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<Portfolio> Portfolio { get; set; }
    }
}
