//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersImage
    {
        public int id { get; set; }
        public int PartnerId { get; set; }
        public int Image { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string VideoUrl { get; set; }
    }
}
