//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.ActionPartner = new HashSet<ActionPartner>();
            this.PartnersRating = new HashSet<PartnersRating>();
            this.User = new HashSet<User>();
            this.PartnerCategory1 = new HashSet<PartnerCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CategoryId { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string TrName { get; set; }
        public Nullable<int> Image { get; set; }
        public Nullable<int> Avatar { get; set; }
        public string City { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Profession { get; set; }
        public string Viezd { get; set; }
        public string Phone { get; set; }
        public string Site { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public string Facebook { get; set; }
        public string Vk { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> ImageProfile { get; set; }
        public int Rate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Moderated { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual ICollection<ActionPartner> ActionPartner { get; set; }
        public virtual ICollection<PartnersRating> PartnersRating { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual Image Image1 { get; set; }
        public virtual Image Image2 { get; set; }
        public virtual Image Image3 { get; set; }
        public virtual PartnerCategory PartnerCategory { get; set; }
        public virtual ICollection<PartnerCategory> PartnerCategory1 { get; set; }
    }
}
