//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public Places()
        {
            this.ActionPlace = new HashSet<ActionPlace>();
            this.Packet = new HashSet<Packet>();
            this.PlaceService = new HashSet<PlaceService>();
            this.Wedding = new HashSet<Wedding>();
            this.Pack = new HashSet<Pack>();
        }
    
        public int Id { get; set; }
        public int DirectionId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountGuests { get; set; }
        public string DaysWedding { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int SmallImage { get; set; }
        public int Image { get; set; }
        public string TrName { get; set; }
        public int Rate { get; set; }
        public bool IsEnabled { get; set; }
        public string PlaceView { get; set; }
        public string City { get; set; }
        public string Panorama { get; set; }
        public string Map { get; set; }
        public string Banket { get; set; }
        public int PlaceTypeId { get; set; }
        public Nullable<bool> IsBeach { get; set; }
    
        public virtual ICollection<ActionPlace> ActionPlace { get; set; }
        public virtual ICollection<Packet> Packet { get; set; }
        public virtual ICollection<PlaceService> PlaceService { get; set; }
        public virtual ICollection<Wedding> Wedding { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Image Image1 { get; set; }
        public virtual Image Image2 { get; set; }
        public virtual ICollection<Pack> Pack { get; set; }
        public virtual PlaceType PlaceType { get; set; }
    }
}
