//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string ShortText { get; set; }
        public int Image { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string LongText { get; set; }
        public Nullable<int> Image2 { get; set; }
        public Nullable<int> Image3 { get; set; }
        public Nullable<int> Image4 { get; set; }
        public Nullable<int> Image5 { get; set; }
        public Nullable<int> Image6 { get; set; }
        public Nullable<int> Image7 { get; set; }
        public Nullable<int> Image8 { get; set; }
        public Nullable<int> Image9 { get; set; }
        public Nullable<int> Image1 { get; set; }
        public string TranslitName { get; set; }
        public int DirectionId { get; set; }
        public Nullable<int> SmallImage { get; set; }
        public string Tag { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<System.DateTime> WedDate { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Image Image10 { get; set; }
        public virtual Image Image11 { get; set; }
        public virtual Image Image12 { get; set; }
        public virtual Image Image13 { get; set; }
        public virtual Image Image14 { get; set; }
        public virtual Image Image15 { get; set; }
        public virtual Image Image16 { get; set; }
        public virtual Image Image17 { get; set; }
        public virtual Image Image18 { get; set; }
        public virtual Image Image19 { get; set; }
        public virtual Image Image20 { get; set; }
        public virtual Partner_old Partner_old { get; set; }
    }
}
