//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedding
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime Date { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string TrName { get; set; }
        public Nullable<int> Image { get; set; }
        public Nullable<int> Avatar { get; set; }
        public string City { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> ImageProfile { get; set; }
        public Nullable<int> Moderated { get; set; }
        public Nullable<int> PlacesId { get; set; }
    
        public virtual Places Places { get; set; }
    }
}
